version: "3"
services:
   dev:
      build: 
         context: .
         dockerfile: Dockerfile
         target: dev-stage
      stdin_open: true
      tty: true
      ports:
         - "5001:5001"
      volumes:
         - "/app/node_modules"
         - ".:/app"
   prod:
      build: 
         context: .
         dockerfile: Dockerfile
         target: prod-stage
      stdin_open: true
      tty: true
      ports:
         - "5002:80"